name: Build
on:
    workflow_dispatch:
    push:
        branches:
            - "**"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - run: npm install --frozen-lockfile
            - run: npm run test
            - run: npm run build